name: pushtoec2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: linux-latest

    steps:
      - name: Checkout the code
      - uses: actions/checkout@v1

      - name: Build the docker image
        uses: docker build -t nginx_pranay .

      - name: Run the docker image
        uses: docker run --name mynginx3 -p 80:80 -d nginx_pranay

   
          