name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: linux-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Build the docker image
        uses: docker build -t mynginx_image1 .

      - name: Run the docker image
        uses: docker run --name mynginx3 -p 80:80 -d mynginx_image1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-3-83-207-16.compute-1.amazonaws.com"
          REMOTE_USER: "ec2-user"
          